import os
import json
import base64
import re
import requests

# Gemini API Model Endpoints
PRIMARY_MODEL = "gemini-2.5-flash"
FALLBACK_MODEL = "gemini-1.5-flash"

def load_env_file():
    """Simple parser to load .env into os.environ if not already present."""
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    if os.path.exists(env_path):
        try:
            with open(env_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    if "=" in line:
                        k, v = line.split("=", 1)
                        k = k.strip()
                        v = v.strip().strip('"').strip("'")
                        if k and not os.environ.get(k):
                            os.environ[k] = v
        except Exception:
            pass

load_env_file()

def get_gemini_api_key(custom_key=None):
    """Retrieve Gemini API key with priority: custom_key -> session/env -> .env file."""
    if custom_key and custom_key.strip():
        return custom_key.strip()
    return os.environ.get("GEMINI_API_KEY", "").strip()

def call_gemini_api(prompt, system_instruction=None, api_key=None, model=PRIMARY_MODEL, image_data=None, mime_type="image/jpeg", json_mode=False):
    """
    Direct HTTP request to Google Gemini API.
    Supports text generation, system instruction, and multimodal vision (receipt scanner).
    """
    key = get_gemini_api_key(api_key)
    if not key:
        return {"error": "NO_API_KEY", "message": "Gemini API key is not configured."}

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}"

    parts = []
    if image_data:
        b64_str = base64.b64encode(image_data).decode("utf-8") if isinstance(image_data, bytes) else image_data
        parts.append({
            "inline_data": {
                "mime_type": mime_type,
                "data": b64_str
            }
        })
    parts.append({"text": prompt})

    payload = {
        "contents": [{"parts": parts}],
        "generationConfig": {
            "temperature": 0.4 if json_mode else 0.7,
            "topP": 0.95
        }
    }

    if system_instruction:
        payload["system_instruction"] = {
            "parts": [{"text": system_instruction}]
        }

    if json_mode:
        payload["generationConfig"]["response_mime_type"] = "application/json"

    headers = {"Content-Type": "application/json"}

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=25)
        if response.status_code == 200:
            data = response.json()
            candidates = data.get("candidates", [])
            if candidates:
                content = candidates[0].get("content", {})
                parts = content.get("parts", [])
                if parts and "text" in parts[0]:
                    return {"success": True, "text": parts[0]["text"], "model": model}
            return {"error": "EMPTY_RESPONSE", "message": "No response text generated by Gemini."}
        elif response.status_code == 404 and model == PRIMARY_MODEL:
            # Fallback to secondary model if primary model is unavailable in this region
            return call_gemini_api(prompt, system_instruction, api_key, model=FALLBACK_MODEL, image_data=image_data, mime_type=mime_type, json_mode=json_mode)
        else:
            err_json = {}
            try:
                err_json = response.json()
            except Exception:
                pass
            err_msg = err_json.get("error", {}).get("message", response.text)
            return {"error": f"API_ERROR_{response.status_code}", "message": err_msg}
    except Exception as e:
        return {"error": "REQUEST_FAILED", "message": str(e)}


# -------------------------------------------------------------
# 1. AI ITINERARY & DESTINATION RECOMMENDER
# -------------------------------------------------------------
def generate_itinerary(destination, origin="Current Location", days=3, travel_style="Balanced", travelers=1, budget=None, api_key=None):
    """Generates day-by-day smart itinerary with sights, food spots, hidden gems, and tips."""
    key = get_gemini_api_key(api_key)
    
    prompt = f"""
    Create a comprehensive, exciting, and realistic {days}-day travel itinerary for a trip from {origin} to {destination}.
    Travelers: {travelers}
    Travel Style: {travel_style}
    Estimated Budget: ₹{budget if budget else 'Standard'}

    Return ONLY a valid JSON object matching this schema:
    {{
        "destination": "{destination}",
        "tagline": "A catchy inspiring tagline for the trip",
        "best_season": "e.g. October to March",
        "ideal_duration": "{days} Days",
        "weather_advice": "Short weather summary and clothing advice",
        "packing_essentials": ["Item 1", "Item 2", "Item 3", "Item 4"],
        "days": [
            {{
                "day_number": 1,
                "title": "Theme of Day 1",
                "morning": "Morning sights, activities & estimated time",
                "afternoon": "Afternoon exploration, museum or adventure",
                "evening": "Sunset point, evening stroll or market",
                "meal_recommendation": "Famous local dish or spot to try today",
                "daily_spend_estimate": "e.g. ₹800 - ₹1200"
            }}
        ],
        "hidden_gems": [
            {{
                "name": "Gem Name",
                "why_visit": "Unique reason to visit",
                "entry_tip": "Best time or ticket tip"
            }}
        ],
        "local_dishes": [
            "Local Dish 1", "Local Dish 2", "Local Dish 3"
        ],
        "smart_budget_tips": [
            "Budget tip 1", "Budget tip 2", "Budget tip 3"
        ]
    }}
    Ensure exactly {days} days in the days array.
    """

    if key:
        res = call_gemini_api(prompt, system_instruction="You are an expert travel planner and local guide for India and international travel.", api_key=key, json_mode=True)
        if res.get("success"):
            try:
                clean_text = res["text"].strip()
                if clean_text.startswith("```json"):
                    clean_text = clean_text[7:]
                if clean_text.endswith("```"):
                    clean_text = clean_text[:-3]
                parsed = json.loads(clean_text.strip())
                parsed["is_ai_live"] = True
                return parsed
            except Exception:
                pass

    # High quality fallback itinerary if API key not provided or request fails
    return get_fallback_itinerary(destination, origin, days, travel_style, travelers, budget)


def get_fallback_itinerary(destination, origin, days, travel_style, travelers, budget):
    """Deterministic, rich fallback itinerary generator."""
    dest_clean = destination.strip() if destination else "Destination"
    days_count = max(1, min(int(days or 3), 7))
    
    sample_days = []
    themes = [
        ("Heritage & Iconic Landmarks", "Explore the historic core, visit the primary architectural marvels and heritage monuments.", "Local culinary tour, sample street food or heritage thali, explore artisan handicraft bazaars.", "Panoramic sunset viewpoint followed by evening cultural show or illuminated monument walk.", "Traditional thali & famous local sweets", "₹900 - ₹1,400"),
        ("Nature, Scenery & Hidden Trails", "Early morning sunrise walk, botanical gardens or scenic lake promenade.", "Scenic riverfront, viewpoint hike or peaceful heritage temple complex.", "Night market shopping, souvenir browsing and live music cafe dinner.", "Regional specialty curry & fresh local breads", "₹700 - ₹1,200"),
        ("Culture, Arts & Local Experiences", "Visit local art galleries, historic museums or palace grounds.", "Handicraft workshops, spice markets or tea/coffee plantation walk.", "Rooftop dining with city views, relaxing stroll along promenade.", "Authentic regional dessert & street delicacies", "₹850 - ₹1,350"),
        ("Offbeat Discovery & Leisure", "Quiet morning visit to outskirts viewpoint or serene spiritual shrine.", "Adventure activity, boat ride or scenic countryside drive.", "Farewell dinner at iconic local diner, pack souvenirs.", "Wood-fired local delicacies or coastal seafood", "₹1,000 - ₹1,600")
    ]

    for i in range(1, days_count + 1):
        idx = (i - 1) % len(themes)
        t = themes[idx]
        sample_days.append({
            "day_number": i,
            "title": f"Day {i}: {t[0]} in {dest_clean.split(',')[0]}",
            "morning": t[1],
            "afternoon": t[2],
            "evening": t[3],
            "meal_recommendation": t[4],
            "daily_spend_estimate": t[5]
        })

    return {
        "destination": dest_clean,
        "tagline": f"Experience the best of {dest_clean.split(',')[0]} with curated daily highlights",
        "best_season": "October to March (Pleasant weather)",
        "ideal_duration": f"{days_count} Days",
        "weather_advice": "Comfortable cotton clothes for daytime; light jacket for evenings. Sturdy walking shoes recommended.",
        "packing_essentials": ["Comfortable walking footwear", "Reusable water bottle", "Sunscreen & sunglasses", "Power bank for photography"],
        "days": sample_days,
        "hidden_gems": [
            {"name": f"{dest_clean.split(',')[0]} Heritage Quarter", "why_visit": "Less crowded alleyways with vibrant architecture and artisan workshops.", "entry_tip": "Best explored early morning before 9 AM."},
            {"name": "Scenic Sunset Point", "why_visit": "Overlooks the entire city landscape with golden hour reflections.", "entry_tip": "Arrive 30 minutes before sunset for the best spot."}
        ],
        "local_dishes": ["Regional Heritage Thali", "Street Food Specialties", "Fresh Local Tea & Snacks"],
        "smart_budget_tips": [
            "Use public transit or shared autos for short hops instead of private cabs.",
            "Book monument tickets online through government portals for express entry and small discounts.",
            "Eat at celebrated local eateries rather than tourist-heavy hotel buffets."
        ],
        "is_ai_live": False
    }


# -------------------------------------------------------------
# 2. AI BUDGET OPTIMIZER & COST ESTIMATOR
# -------------------------------------------------------------
def estimate_destination_costs(destination, origin="Bengaluru", travelers=1, days=2, transport_mode="car", api_key=None):
    """Uses Gemini to estimate realistic room, food, toll, and ticket expenses."""
    key = get_gemini_api_key(api_key)
    
    prompt = f"""
    Estimate realistic travel expenses in Indian Rupees (INR ₹) for a trip from {origin} to {destination}.
    Travelers: {travelers}
    Duration: {days} days
    Transport Mode: {transport_mode}

    Return ONLY a JSON object with this exact format:
    {{
        "room_cost_per_night": 2200,
        "food_cost_per_person_per_day": 650,
        "estimated_tolls_total": 450,
        "estimated_entry_fees_total": 300,
        "estimated_parking_total": 150,
        "tier_category": "Budget-Friendly / Mid-Range / Luxury",
        "summary": "Brief 1-sentence explanation of cost characteristics of this destination",
        "saving_tip": "Top actionable tip to reduce expenses on this trip"
    }}
    Numbers must be raw integers without currency symbols.
    """

    if key:
        res = call_gemini_api(prompt, system_instruction="You are a precise travel cost estimator for Indian and global tourism.", api_key=key, json_mode=True)
        if res.get("success"):
            try:
                clean_text = res["text"].strip()
                if clean_text.startswith("```json"):
                    clean_text = clean_text[7:]
                if clean_text.endswith("```"):
                    clean_text = clean_text[:-3]
                parsed = json.loads(clean_text.strip())
                parsed["is_ai_live"] = True
                return parsed
            except Exception:
                pass

    # Intelligent fallback calculation based on destination name tier
    dest_lower = (destination or "").lower()
    is_premium = any(c in dest_lower for c in ["goa", "mumbai", "delhi", "manali", "munnar", "shimla", "udaipur", "ladakh"])
    is_mid = any(c in dest_lower for c in ["chennai", "hyderabad", "bengaluru", "kolkata", "pune", "jaipur", "kochi", "agra", "mysuru", "coorg", "ooty"])
    
    room_rate = 3200 if is_premium else (2400 if is_mid else 1600)
    food_rate = 850 if is_premium else (650 if is_mid else 450)
    tolls = 600 if transport_mode in ["car", "rental"] else 0
    entry_fees = 350 * int(travelers or 1)
    parking = 150 if transport_mode in ["car", "rental", "bike"] else 0

    return {
        "room_cost_per_night": room_rate,
        "food_cost_per_person_per_day": food_rate,
        "estimated_tolls_total": tolls,
        "estimated_entry_fees_total": entry_fees,
        "estimated_parking_total": parking,
        "tier_category": "Premium Tourist Destination" if is_premium else ("Mid-Range Popular City" if is_mid else "Budget-Friendly Destination"),
        "summary": f"{destination.split(',')[0]} offers competitive rates with diverse stay and dining options.",
        "saving_tip": "Book homestays or budget hotels in advance and eat at authentic local diners.",
        "is_ai_live": False
    }


def analyze_and_optimize_budget(trip_data, api_key=None):
    """Reviews current trip budget and suggests 3-4 specific high-impact saving strategies."""
    key = get_gemini_api_key(api_key)
    
    prompt = f"""
    Analyze this travel budget breakdown and recommend specific actionable ways to optimize and reduce costs:
    Destination: {trip_data.get('destination')}
    Travelers: {trip_data.get('travelers')}
    Distance: {trip_data.get('total_distance')} km
    Transport: {trip_data.get('transport_mode')} (Cost: ₹{trip_data.get('transport_cost', 0)})
    Stay Cost: ₹{trip_data.get('room_cost', 0)}
    Food Cost: ₹{trip_data.get('food_cost', 0)}
    Toll Charges: ₹{trip_data.get('toll_charges', 0)}
    Entry Fees: ₹{trip_data.get('places_fee_total', 0)}
    Total Budget: ₹{trip_data.get('total_budget', 0)} (₹{trip_data.get('cost_per_person', 0)}/person)

    Return ONLY a JSON object:
    {{
        "overall_rating": "Great / Reasonable / Slightly High / Premium",
        "potential_savings": 1500,
        "highest_expense_category": "Stay / Transport / Food",
        "analysis": "2 sentence summary of spending efficiency",
        "recommendations": [
            {{
                "category": "Transport / Stay / Food / Activities",
                "title": "Clear action title",
                "description": "Specific detail on what to do",
                "estimated_saving_inr": 600
            }}
        ]
    }}
    """

    if key:
        res = call_gemini_api(prompt, system_instruction="You are a frugal travel cost hacker and budget optimization expert.", api_key=key, json_mode=True)
        if res.get("success"):
            try:
                clean_text = res["text"].strip()
                if clean_text.startswith("```json"):
                    clean_text = clean_text[7:]
                if clean_text.endswith("```"):
                    clean_text = clean_text[:-3]
                parsed = json.loads(clean_text.strip())
                parsed["is_ai_live"] = True
                return parsed
            except Exception:
                pass

    total = float(trip_data.get("total_budget", 0) or 0)
    savings = round(total * 0.18) if total > 2000 else 400

    return {
        "overall_rating": "Reasonable & Well-Balanced",
        "potential_savings": savings,
        "highest_expense_category": "Stay & Transport",
        "analysis": f"Your planned budget for {trip_data.get('destination', 'this trip')} is balanced. We found opportunities to save up to ₹{savings:,} without sacrificing comfort.",
        "recommendations": [
            {
                "category": "Stay",
                "title": "Choose Verified Homestays or Guesthouses",
                "description": "Booking boutique guesthouses or Airbnb homestays 1-2 km outside city center saves 25-35% on room rates.",
                "estimated_saving_inr": round(savings * 0.5)
            },
            {
                "category": "Food",
                "title": "Eat at Iconic Local Eateries",
                "description": "Opt for renowned local diners and thali joints for lunch instead of hotel dining.",
                "estimated_saving_inr": round(savings * 0.3)
            },
            {
                "category": "Tolls & Fuel",
                "title": "Maintain Efficient Cruising Speed & Fastag Discounts",
                "description": "Steady cruising at 80-90 km/h improves mileage by 15%, reducing fuel bills significantly.",
                "estimated_saving_inr": round(savings * 0.2)
            }
        ],
        "is_ai_live": False
    }


# -------------------------------------------------------------
# 3. INTERACTIVE AI TRAVEL CHATBOT
# -------------------------------------------------------------
def chat_with_assistant(user_message, history=None, trip_context=None, api_key=None):
    """Context-aware conversational assistant for travel guidance, food, packing, and budget questions."""
    key = get_gemini_api_key(api_key)
    
    ctx_str = ""
    if trip_context:
        ctx_str = f"""
        User's Current Trip Context:
        - Origin: {trip_context.get('origin', 'Not specified')}
        - Destination: {trip_context.get('destination', 'Not specified')}
        - Travelers: {trip_context.get('travelers', 1)}
        - Transport: {trip_context.get('transport_mode', 'car')}
        - Distance: {trip_context.get('distance', 'N/A')} km
        - Total Estimated Budget: ₹{trip_context.get('total_budget', 'N/A')}
        """

    system_prompt = f"""
    You are TravelAI Copilot, the intelligent and friendly AI assistant inside the Travel Budget Planner web application.
    You assist travelers with destination tips, day itineraries, budget optimization, hidden spots, local food recommendations, packing checklists, and route advice.
    Keep answers structured, concise, warm, and practical. Use bullet points and emoji highlights where helpful.
    Always quote costs in Indian Rupees (₹) when discussing Indian destinations.
    {ctx_str}
    """

    # Build conversation prompt
    conv_prompt = ""
    if history and isinstance(history, list):
        for msg in history[-6:]: # Keep last 6 turns for context
            role = "User" if msg.get("role") == "user" else "Assistant"
            conv_prompt += f"{role}: {msg.get('text', '')}\n"
    conv_prompt += f"User: {user_message}\nAssistant:"

    if key:
        res = call_gemini_api(conv_prompt, system_instruction=system_prompt, api_key=key)
        if res.get("success"):
            return {"reply": res["text"], "is_ai_live": True}

    # Smart contextual fallback replies
    msg_lower = user_message.lower()
    dest = (trip_context.get("destination") if trip_context else "") or "your destination"
    
    if any(w in msg_lower for w in ["food", "eat", "restaurant", "dish", "cuisine"]):
        reply = f"🍛 **Top Food Recommendations for {dest.split(',')[0]}:**\n\n" \
                f"1. **Signature Local Thali**: Don't miss the authentic traditional thali at historic city eateries.\n" \
                f"2. **Street Food Hotspots**: Explore the evening food street for fresh savories, sweets, and hot chai.\n" \
                f"3. **Budget Tip**: Avoid in-hotel dining; local family-run restaurants are half the price and twice as authentic!"
    elif any(w in msg_lower for w in ["pack", "luggage", "cloth", "wear"]):
        reply = f"🎒 **Packing Essentials for {dest.split(',')[0]}:**\n\n" \
                f"- **Footwear**: Sturdy, broken-in walking shoes or sneakers for exploring.\n" \
                f"- **Apparel**: Breathable lightweight cottons for day; a light jacket or shawl for air-conditioned transit & cool evenings.\n" \
                f"- **Gear**: 20,000mAh Power bank, reusable insulated water bottle, and a compact umbrella.\n" \
                f"- **Documents**: Government Photo ID, emergency cash, and offline downloaded maps."
    elif any(w in msg_lower for w in ["save", "budget", "cheap", "cost", "money"]):
        reply = f"💡 **Top 3 Money-Saving Hacks for {dest.split(',')[0]}:**\n\n" \
                f"1. **Book Stay Early**: Off-center homestays or boutique hostels can save ₹1,000 - ₹2,000 per night.\n" \
                f"2. **Public Transit & Passes**: Use metro, city buses, or shared rides for local commutes instead of hailing private cabs.\n" \
                f"3. **Free & Low-Cost Sights**: Public gardens, temple complexes, walking streets, and sunset viewpoints offer world-class experiences at ₹0 entry!"
    elif any(w in msg_lower for w in ["itinerary", "plan", "schedule", "days"]):
        reply = f"🗺️ **Quick Itinerary Outline for {dest.split(',')[0]}:**\n\n" \
                f"- **Morning**: Visit iconic heritage monuments early (8:30 - 11:00 AM) before crowds and heat arrive.\n" \
                f"- **Afternoon**: Air-conditioned museum, artisan craft market, or a peaceful shaded garden.\n" \
                f"- **Evening**: Head to the best local viewpoint for sunset, followed by bustling night bazaar exploration!\n\n" \
                f"*(Click '✨ Generate AI Itinerary' in the AI Hub to get a complete day-by-day plan!)*"
    else:
        reply = f"Hello! 👋 I'm your **TravelAI Copilot**.\n\n" \
                f"I can help you plan your journey to **{dest.split(',')[0]}**, find hidden attractions, calculate realistic budgets, suggest local food specialties, or optimize your expenses.\n\n" \
                f"What would you like to know about your trip?"

    return {
        "reply": reply,
        "is_ai_live": False
    }


# -------------------------------------------------------------
# 4. AI RECEIPT & EXPENSE SCANNER (VISION AI)
# -------------------------------------------------------------
def scan_receipt_with_vision(image_bytes, mime_type="image/jpeg", api_key=None):
    """
    Multimodal Vision analysis of receipt / invoice / ticket.
    Extracts vendor, category, date, total amount, taxes, and line items.
    """
    key = get_gemini_api_key(api_key)
    
    prompt = """
    Analyze this travel receipt, invoice, fuel chit, or ticket image.
    Extract the financial details into this exact JSON format:
    {
        "vendor_name": "Name of the business / station / hotel",
        "date": "YYYY-MM-DD or readable date string",
        "category": "Fuel / Food / Room / Toll / Parking / Entry / Transit / Miscellaneous",
        "currency": "INR",
        "total_amount": 1250.00,
        "tax_amount": 62.50,
        "items": [
            {"description": "Item description", "amount": 1250.00}
        ],
        "notes": "Short description of the expense or verification note"
    }
    Ensure total_amount and tax_amount are numeric floats. If tax is not visible, use 0.0.
    Return ONLY valid JSON.
    """

    if key:
        res = call_gemini_api(
            prompt=prompt,
            system_instruction="You are an expert OCR receipt and invoice parser specializing in travel expenses.",
            api_key=key,
            image_data=image_bytes,
            mime_type=mime_type,
            json_mode=True
        )
        if res.get("success"):
            try:
                clean_text = res["text"].strip()
                if clean_text.startswith("```json"):
                    clean_text = clean_text[7:]
                if clean_text.endswith("```"):
                    clean_text = clean_text[:-3]
                parsed = json.loads(clean_text.strip())
                parsed["is_ai_live"] = True
                return parsed
            except Exception:
                pass

    # Fallback simulated OCR parser if key is not active or image unrecognized
    return {
        "vendor_name": "Travel Expense Receipt",
        "date": "Recent",
        "category": "Food",
        "currency": "INR",
        "total_amount": 450.00,
        "tax_amount": 22.50,
        "items": [
            {"description": "Travel Meals & Refreshments", "amount": 427.50},
            {"description": "GST / Service Charge", "amount": 22.50}
        ],
        "notes": "Receipt scanned in demo mode. Configure your free Gemini API Key in AI Settings for live Vision OCR extraction.",
        "is_ai_live": False
    }
